// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class upd_UserTokens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd_UserTokens));
        
        string IMigrationMetadata.Id
        {
            get { return "201612131307123_upd_UserTokens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
